In [153]:
import requests
import pandas as pd

In [154]:
def obtener_monumentos():
    url = "https://datos.madrid.es/egob/catalogo/300356-0-monumentos-ciudad-madrid.csv"
    
    try:
        response = requests.get(url)
        response.raise_for_status()  # Verifica si la solicitud fue exitosa

        # Si la solicitud es exitosa, retorna el contenido en formato CSV
        return response.content

    except requests.exceptions.RequestException as e:
        print("Error al obtener los monumentos:", e)
        return None

In [155]:
contenido_csv = obtener_monumentos()

# Verificar si se obtuvo el contenido y guardarlo en un archivo CSV
if contenido_csv:
    with open("../data/madrid/Monumentos/monumentos.csv", "wb") as archivo_csv:
        archivo_csv.write(contenido_csv)
    print("Se ha guardado el archivo monumentos.csv")

Se ha guardado el archivo monumentos.csv

In [156]:
df = pd.read_csv("../data/madrid/Monumentos/monumentos.csv", sep=";", encoding="latin-1")

In [157]:
df

,PK,NOMBRE,SUBTIPO,DESCRIPCION,FECHA,AUTORES,PDF,CONTENT-URL,NOMBRE-VIA,CLASE-VIAL,...,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,FAX,EMAIL,TIPO,Unnamed: 31
0,409634,A las víctimas del Holocausto,Escultura conceptual o abstracta,"La obra, creada por el escultor judío de orige...",2005,"NAHÓN BENGIO, Samuel - STISIN, Alberto",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,TRES CULTURAS,JARDIN,...,DISTRITO,448830.0,4479469.0,40.464322,-3.603558,NaN,NaN,NaN,NaN,
1,409512,A los Abuelos,Grupo Escultórico,"Pequeña escultura, situada en un parque delimi...",1994,"M., Esther",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,Alicún,C,...,HORTALEZA,443913.0,4481224.0,40.479812,-3.661719,NaN,NaN,NaN,NaN,
2,408781,A Neruda-El Ser alado,Estatua,Monumento dedicado al escritor Pablo Neruda (1...,1988,"QUETGLÁS, Matías",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,José Luis Ozores,Gta,...,PUENTE DE VALLECAS,444621.0,4470345.0,40.381855,-3.652419,NaN,NaN,NaN,NaN,
3,408836,Abogados Laboristas,"Elemento conmemorativo, Lápida",El 24 de enero de 1977 se produjo un atentado ...,1987,"ROLDÁN PASCUAL, Joaquín",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,Atocha,C,...,CENTRO,440608.0,4473823.0,40.412911,-3.700017,NaN,NaN,NaN,NaN,
4,408920,Abstracta I,Escultura conceptual o abstracta,"La histórica quinta de la Fuente del Berro, de...",1992,"GONZÁLEZ CALISAVO, Fernando",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,NaN,NaN,...,SALAMANCA,443926.0,4474987.0,40.421746,-3.662293,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1827,409830,Álvaro Iglesias Sánchez,"Elemento conmemorativo, Lápida",El 6 de abril de 1982 se produjo un incendio e...,1982,"JIMÉNEZ, L.",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,CARRANZA,CALLE,...,CENTRO,440358.0,4475611.0,40.429000,-3.703131,NaN,NaN,NaN,NaN,
1828,408375,Ángeles de la Paz,Grupo Escultórico,"Este monumento, proyectado en chapa de hierro ...",1964,"ESPINOS ALONSO, José",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,Bruselas,Avda,...,SALAMANCA,443676.0,4477142.0,40.443023,-3.664153,NaN,NaN,NaN,NaN,
1829,409037,Árbol de la Vida,"Puerta, Arco triunfal",El Jardín de las Tres Culturas es un ámbito es...,1990,"ESTEBAN PENELAS, José Luis - ESTERAS MARTÍN, E...",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,TRES CULTURAS,JARDIN,...,DISTRITO,448830.0,4479469.0,40.464322,-3.603558,NaN,NaN,NaN,NaN,
1830,408008,Íñigo Arista,Estatua,Forma parte esta escultura de la serie concebi...,1750,"OÑATE, José",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,Oriente,Pza,...,CENTRO,439581.0,4474364.0,40.417710,-3.712172,NaN,NaN,NaN,NaN,
1831,400117,Órgano,Escultura conceptual o abstracta,En 1971 el arquitecto José Luis Picardo ganó e...,1977,"SEMPERE JUAN, Eusebio",https://patrimonioypaisaje.madrid.es/FrameWork...,https://patrimonioypaisaje.madrid.es/sites/v/i...,Castelló,C,...,SALAMANCA,442223.0,4475831.0,40.431113,-3.681166,NaN,NaN,NaN,NaN,

In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1832 entries, 0 to 1831
Data columns (total 32 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PK             1832 non-null   int64
 1   NOMBRE         1832 non-null   object
 2   SUBTIPO        1832 non-null   object
 3   DESCRIPCION    1831 non-null   object
 4   FECHA          1813 non-null   object
 5   AUTORES        916 non-null    object
 6   PDF            1832 non-null   object
 7   CONTENT-URL    1832 non-null   object
 8   NOMBRE-VIA     1586 non-null   object
 9   CLASE-VIAL     1582 non-null   object
 10  TIPO-NUM       1830 non-null   object
 11  NUM            883 non-null    object
 12  PLANTA         0 non-null      float64
 13  PUERTA         0 non-null      float64
 14  ESCALERAS      0 non-null      float64
 15  ORIENTACION    0 non-null      float64
 16  LOCALIDAD      1829 non-null   object
 17  PROVINCIA      1829 non-null   object
 18  CODIGO-POSTAL  348 non-null    float64
 19  COD-BARRIO     1350 non-null   float64
 20  BARRIO         1696 non-null   object
 21  COD-DISTRITO   1350 non-null   float64
 22  DISTRITO       1829 non-null   object
 23  COORDENADA-X   1829 non-null   float64
 24  COORDENADA-Y   1829 non-null   float64
 25  LATITUD        1776 non-null   float64
 26  LONGITUD       1776 non-null   float64
 27  TELEFONO       0 non-null      float64
 28  FAX            0 non-null      float64
 29  EMAIL          0 non-null      float64
 30  TIPO           0 non-null      float64
 31  Unnamed: 31    1832 non-null   object
dtypes: float64(15), int64(1), object(16)
memory usage: 458.1+ KB

In [159]:
df.dropna(subset=["LONGITUD"], inplace=True)
df.dropna(subset=["LOCALIDAD"], inplace=True)

In [160]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1775 entries, 0 to 1831
Data columns (total 32 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PK             1775 non-null   int64
 1   NOMBRE         1775 non-null   object
 2   SUBTIPO        1775 non-null   object
 3   DESCRIPCION    1774 non-null   object
 4   FECHA          1757 non-null   object
 5   AUTORES        877 non-null    object
 6   PDF            1775 non-null   object
 7   CONTENT-URL    1775 non-null   object
 8   NOMBRE-VIA     1579 non-null   object
 9   CLASE-VIAL     1576 non-null   object
 10  TIPO-NUM       1775 non-null   object
 11  NUM            880 non-null    object
 12  PLANTA         0 non-null      float64
 13  PUERTA         0 non-null      float64
 14  ESCALERAS      0 non-null      float64
 15  ORIENTACION    0 non-null      float64
 16  LOCALIDAD      1775 non-null   object
 17  PROVINCIA      1775 non-null   object
 18  CODIGO-POSTAL  348 non-null    float64
 19  COD-BARRIO     1299 non-null   float64
 20  BARRIO         1642 non-null   object
 21  COD-DISTRITO   1299 non-null   float64
 22  DISTRITO       1774 non-null   object
 23  COORDENADA-X   1774 non-null   float64
 24  COORDENADA-Y   1774 non-null   float64
 25  LATITUD        1775 non-null   float64
 26  LONGITUD       1775 non-null   float64
 27  TELEFONO       0 non-null      float64
 28  FAX            0 non-null      float64
 29  EMAIL          0 non-null      float64
 30  TIPO           0 non-null      float64
 31  Unnamed: 31    1775 non-null   object
dtypes: float64(15), int64(1), object(16)
memory usage: 457.6+ KB

In [161]:
# df = df.drop(["PDF","CONTENT-URL","TIPO-NUM","PLANTA","PUERTA","ESCALERAS","ORIENTACION","LOCALIDAD","PROVINCIA",
#               "CODIGO-POSTAL","COD-BARRIO","COD-DISTRITO","TELEFONO","FAX","EMAIL","TIPO","Unnamed: 31"],axis=1)

In [162]:
df = df.drop(["PK","PDF","CONTENT-URL","TIPO-NUM","PLANTA","PUERTA","ESCALERAS","ORIENTACION","LOCALIDAD","PROVINCIA",
              "CODIGO-POSTAL","COD-BARRIO","COD-DISTRITO","TELEFONO","FAX","EMAIL","Unnamed: 31","AUTORES","TIPO","COORDENADA-X",
              "COORDENADA-Y","BARRIO","FECHA","DESCRIPCION"],axis=1)

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1775 entries, 0 to 1831
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   NOMBRE      1775 non-null   object
 1   SUBTIPO     1775 non-null   object
 2   NOMBRE-VIA  1579 non-null   object
 3   CLASE-VIAL  1576 non-null   object
 4   NUM         880 non-null    object
 5   DISTRITO    1774 non-null   object
 6   LATITUD     1775 non-null   float64
 7   LONGITUD    1775 non-null   float64
dtypes: float64(2), object(6)
memory usage: 124.8+ KB

In [164]:
df[df["CLASE-VIAL"].isna()]

,NOMBRE,SUBTIPO,NOMBRE-VIA,CLASE-VIAL,NUM,DISTRITO,LATITUD,LONGITUD
4,Abstracta I,Escultura conceptual o abstracta,NaN,NaN,NaN,SALAMANCA,40.421746,-3.662293
5,Abstracta II,Escultura conceptual o abstracta,NaN,NaN,NaN,SALAMANCA,40.421962,-3.662260
22,Al Maestro,Grupo Escultórico,NaN,NaN,NaN,MONCLOA-ARAVACA,40.432498,-3.727513
33,Alfonso R. Castelao,"Elemento conmemorativo, Lápida",NaN,NaN,NaN,SALAMANCA,40.435503,-3.660683
34,Alfonso VI,Estatua,NaN,NaN,NaN,CENTRO,40.419736,-3.713926
...,...,...,...,...,...,...,...,...
1785,Vagón-plataforma de tren,Elemento de ornamentación,NaN,NaN,NaN,ARGANZUELA,40.393835,-3.685479
1795,Venus emergiendo de las aguas,Escultura conceptual o abstracta,NaN,NaN,NaN,USERA,40.372427,-3.703885
1801,Viga,Escultura conceptual o abstracta,NaN,NaN,NaN,BARAJAS,40.461618,-3.613677
1803,Virgen Blanca (Virgen del Asedio),Estatua,NaN,NaN,NaN,MONCLOA-ARAVACA,40.439345,-3.721703
1812,Vías de tren,"Elemento conmemorativo, Lápida",NaN,NaN,NaN,MORATALAZ,40.408428,-3.638603

In [165]:
# # df["DESCRIPCION"] = df["DESCRIPCION"].fillna("No disponible")
# df["FECHA"] = df["FECHA"].fillna("No disponible")
# # df["AUTORES"] = df["AUTORES"].fillna("No disponible")
# df["NUM"] = df["NUM"].fillna("No disponible")
# df["BARRIO"] = df["BARRIO"].fillna("No disponible")
# df["DISTRITO"] = df["DISTRITO"].fillna("No disponible")
# df["NOMBRE-VIA"] = df["NOMBRE-VIA"].fillna("No disponible")
# df["CLASE-VIAL"] = df["CLASE-VIAL"].fillna("No disponible")

In [166]:
df["NUM"] = df["NUM"].fillna("N/A o N/D")
df["DISTRITO"] = df["DISTRITO"].fillna("No disponible")
df["NOMBRE-VIA"] = df["NOMBRE-VIA"].fillna("No disponible")
df["CLASE-VIAL"] = df["CLASE-VIAL"].fillna("No disponible")

In [167]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1775 entries, 0 to 1831
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   NOMBRE      1775 non-null   object
 1   SUBTIPO     1775 non-null   object
 2   NOMBRE-VIA  1775 non-null   object
 3   CLASE-VIAL  1775 non-null   object
 4   NUM         1775 non-null   object
 5   DISTRITO    1775 non-null   object
 6   LATITUD     1775 non-null   float64
 7   LONGITUD    1775 non-null   float64
dtypes: float64(2), object(6)
memory usage: 124.8+ KB

In [168]:
# # Intercambiamos el orden de las columnas 3 y 4 para luego cambiarles el nombre para favorecer la visualización.
# df.iloc[:, [6, 7]] = df.iloc[:, [7, 6]].values

In [169]:
# Intercambiamos el orden de las columnas 3 y 4 para luego cambiarles el nombre para favorecer la visualización.
df.iloc[:, [2, 3]] = df.iloc[:, [3, 2]].values

In [170]:
df.rename(columns={"NOMBRE-VIA": "CLASE-VIA", "CLASE-VIAL": "NOMBRE-VIA"}, inplace=True)

In [171]:
df.head()

,NOMBRE,SUBTIPO,CLASE-VIA,NOMBRE-VIA,NUM,DISTRITO,LATITUD,LONGITUD
0,A las víctimas del Holocausto,Escultura conceptual o abstracta,JARDIN,TRES CULTURAS,N/A o N/D,DISTRITO,40.464322,-3.603558
1,A los Abuelos,Grupo Escultórico,C,Alicún,N/A o N/D,HORTALEZA,40.479812,-3.661719
2,A Neruda-El Ser alado,Estatua,Gta,José Luis Ozores,116,PUENTE DE VALLECAS,40.381855,-3.652419
3,Abogados Laboristas,"Elemento conmemorativo, Lápida",C,Atocha,55,CENTRO,40.412911,-3.700017
4,Abstracta I,Escultura conceptual o abstracta,No disponible,No disponible,N/A o N/D,SALAMANCA,40.421746,-3.662293

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1775 entries, 0 to 1831
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   NOMBRE      1775 non-null   object
 1   SUBTIPO     1775 non-null   object
 2   CLASE-VIA   1775 non-null   object
 3   NOMBRE-VIA  1775 non-null   object
 4   NUM         1775 non-null   object
 5   DISTRITO    1775 non-null   object
 6   LATITUD     1775 non-null   float64
 7   LONGITUD    1775 non-null   float64
dtypes: float64(2), object(6)
memory usage: 124.8+ KB

In [173]:
df["NUM"] = df["NUM"].astype(str)

In [174]:
df["DIRECCION"] = df["CLASE-VIA"] + " " + df["NOMBRE-VIA"] + " " + df["NUM"]

In [175]:
df.drop(["CLASE-VIA","NOMBRE-VIA","NUM"],axis=1,inplace=True)

In [176]:
df = df.loc[df["DISTRITO"].isin(["CENTRO", "CHAMBERI", "RETIRO","ARGANZUELA", "SALAMANCA"])]

In [177]:
df["DESCRIPCION"] = df["SUBTIPO"]

In [178]:
df["TIPO"] = "Monumentos"

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 762 entries, 3 to 1831
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   NOMBRE       762 non-null    object
 1   SUBTIPO      762 non-null    object
 2   DISTRITO     762 non-null    object
 3   LATITUD      762 non-null    float64
 4   LONGITUD     762 non-null    float64
 5   DIRECCION    762 non-null    object
 6   DESCRIPCION  762 non-null    object
 7   TIPO         762 non-null    object
dtypes: float64(2), object(6)
memory usage: 53.6+ KB

In [180]:
df.drop(["SUBTIPO","DISTRITO"],axis=1,inplace=True)

In [181]:
df.head()

,NOMBRE,LATITUD,LONGITUD,DIRECCION,DESCRIPCION,TIPO
3,Abogados Laboristas,40.412911,-3.700017,C Atocha 55,"Elemento conmemorativo, Lápida",Monumentos
4,Abstracta I,40.421746,-3.662293,No disponible No disponible N/A o N/D,Escultura conceptual o abstracta,Monumentos
5,Abstracta II,40.421962,-3.662260,No disponible No disponible N/A o N/D,Escultura conceptual o abstracta,Monumentos
6,Abundancia,40.444201,-3.712595,CALLE GUZMAN EL BUENO 137,Grupo Escultórico,Monumentos
7,Academia de Farmacia,40.423967,-3.699719,C Farmacia 9,"Elemento conmemorativo, Lápida",Monumentos

In [182]:
df[df["DIRECCION"]== "No disponible No disponible N/A o N/D"]

,NOMBRE,LATITUD,LONGITUD,DIRECCION,DESCRIPCION,TIPO
4,Abstracta I,40.421746,-3.662293,No disponible No disponible N/A o N/D,Escultura conceptual o abstracta,Monumentos
5,Abstracta II,40.421962,-3.662260,No disponible No disponible N/A o N/D,Escultura conceptual o abstracta,Monumentos
33,Alfonso R. Castelao,40.435503,-3.660683,No disponible No disponible N/A o N/D,"Elemento conmemorativo, Lápida",Monumentos
34,Alfonso VI,40.419736,-3.713926,No disponible No disponible N/A o N/D,Estatua,Monumentos
35,Alfonso VIII,40.419889,-3.713904,No disponible No disponible N/A o N/D,Estatua,Monumentos
...,...,...,...,...,...,...
1684,Ría Chica,40.423138,-3.661364,No disponible No disponible N/A o N/D,"Fuente, Estanque, Lámina de agua",Monumentos
1710,San Isidro,40.409875,-3.714729,No disponible No disponible N/A o N/D,Grupo Escultórico,Monumentos
1756,Tetraedro-Fuego,40.402612,-3.710599,No disponible No disponible N/A o N/D,Escultura conceptual o abstracta,Monumentos
1757,Thalía,40.414501,-3.677992,No disponible No disponible N/A o N/D,Estatua,Monumentos
1785,Vagón-plataforma de tren,40.393835,-3.685479,No disponible No disponible N/A o N/D,Elemento de ornamentación,Monumentos

In [183]:
df["DIRECCION"].replace("No disponible No disponible N/A o N/D", "No disponible", inplace=True)

In [184]:
df

,NOMBRE,LATITUD,LONGITUD,DIRECCION,DESCRIPCION,TIPO
3,Abogados Laboristas,40.412911,-3.700017,C Atocha 55,"Elemento conmemorativo, Lápida",Monumentos
4,Abstracta I,40.421746,-3.662293,No disponible,Escultura conceptual o abstracta,Monumentos
5,Abstracta II,40.421962,-3.662260,No disponible,Escultura conceptual o abstracta,Monumentos
6,Abundancia,40.444201,-3.712595,CALLE GUZMAN EL BUENO 137,Grupo Escultórico,Monumentos
7,Academia de Farmacia,40.423967,-3.699719,C Farmacia 9,"Elemento conmemorativo, Lápida",Monumentos
...,...,...,...,...,...,...
1825,Álvaro de Bazán,40.415109,-3.710412,Pza Villa N/A o N/D,Estatua,Monumentos
1827,Álvaro Iglesias Sánchez,40.429000,-3.703131,CALLE CARRANZA 7,"Elemento conmemorativo, Lápida",Monumentos
1828,Ángeles de la Paz,40.443023,-3.664153,Avda Bruselas N/A o N/D,Grupo Escultórico,Monumentos
1830,Íñigo Arista,40.417710,-3.712172,Pza Oriente N/A o N/D,Estatua,Monumentos
1831,Órgano,40.431113,-3.681166,C Castelló 77,Escultura conceptual o abstracta,Monumentos

In [185]:
df = df.reindex(columns=['TIPO', 'NOMBRE', 'DIRECCION', 'DESCRIPCION', 'LATITUD', 'LONGITUD'])

In [186]:
df.reset_index(drop=True, inplace=True)

In [187]:
df

,TIPO,NOMBRE,DIRECCION,DESCRIPCION,LATITUD,LONGITUD
0,Monumentos,Abogados Laboristas,C Atocha 55,"Elemento conmemorativo, Lápida",40.412911,-3.700017
1,Monumentos,Abstracta I,No disponible,Escultura conceptual o abstracta,40.421746,-3.662293
2,Monumentos,Abstracta II,No disponible,Escultura conceptual o abstracta,40.421962,-3.662260
3,Monumentos,Abundancia,CALLE GUZMAN EL BUENO 137,Grupo Escultórico,40.444201,-3.712595
4,Monumentos,Academia de Farmacia,C Farmacia 9,"Elemento conmemorativo, Lápida",40.423967,-3.699719
...,...,...,...,...,...,...
757,Monumentos,Álvaro de Bazán,Pza Villa N/A o N/D,Estatua,40.415109,-3.710412
758,Monumentos,Álvaro Iglesias Sánchez,CALLE CARRANZA 7,"Elemento conmemorativo, Lápida",40.429000,-3.703131
759,Monumentos,Ángeles de la Paz,Avda Bruselas N/A o N/D,Grupo Escultórico,40.443023,-3.664153
760,Monumentos,Íñigo Arista,Pza Oriente N/A o N/D,Estatua,40.417710,-3.712172
761,Monumentos,Órgano,C Castelló 77,Escultura conceptual o abstracta,40.431113,-3.681166

In [188]:
nombre_archivo = "../data/madrid/Monumentos/Monumentos_filtrados.csv"

In [189]:
df.to_csv(nombre_archivo)