In [52]:
import requests
import pandas as pd

In [53]:
def obtener_templos_no_catolicos():
    url = "https://datos.madrid.es/egob/catalogo/209434-0-templos-otros.csv"
    
    try:
        response = requests.get(url)
        response.raise_for_status()  # Verifica si la solicitud fue exitosa

        # Si la solicitud es exitosa, retorna el contenido en formato CSV
        return response.content

    except requests.exceptions.RequestException as e:
        print("Error al obtener los templos no católicos:", e)
        return None

In [54]:
contenido_csv = obtener_templos_no_catolicos()

# Verificar si se obtuvo el contenido y guardarlo en un archivo CSV
if contenido_csv:
    with open("../data/madrid/Templos_no_catolicos/templos_no_catolicos.csv", "wb") as archivo_csv:
        archivo_csv.write(contenido_csv)
    print("Se ha guardado el archivo templos_no_catolicos.csv")

Se ha guardado el archivo templos_no_catolicos.csv

In [55]:
df = pd.read_csv("../data/madrid/Templos_no_catolicos/templos_no_catolicos.csv", sep=";", encoding="latin-1")

In [56]:
df

,PK,NOMBRE,DESCRIPCION-ENTIDAD,HORARIO,EQUIPAMIENTO,TRANSPORTE,DESCRIPCION,ACCESIBILIDAD,CONTENT-URL,NOMBRE-VIA,...,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,FAX,EMAIL,TIPO,Unnamed: 32
0,11772877,Asamblea Cristiana Gilgal,Templo evangélico.,NaN,NaN,"Bus: 141, 133, 8.",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,GARGANTA DE AISA,...,PUENTE DE VALLECAS,444200,4472697,40.403023,-3.657575,NaN,NaN,NaN,/contenido/entidadesYorganismos/TemplosOtrasRe...,
1,11025958,Asambleas de Evangelización Mundial para Crist...,Templo evangélico,NaN,NaN,"Metro: San Francisco (línea 11) Bus: 108, 118...",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,ANTONIA RODRIGUEZ SACRISTAN,...,CARABANCHEL,436747,4469402,40.372800,-3.745074,NaN,NaN,NaN,/contenido/entidadesYorganismos/TemplosOtrasRe...,
2,11026848,Asociación Evangélica Internacional,Templo evangélico.,NaN,NaN,"Metro: Colombia (líneas 8 y 9). Bus: 52, 11, ...",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,NICARAGUA,...,CHAMARTIN,443135,4478797,40.457895,-3.670675,NaN,NaN,NaN,/contenido/entidadesYorganismos/TemplosOtrasRe...,
3,3387,Catedral Anglicana de Madrid,Iglesia Española Reformada Episcopal Comunión ...,NaN,NaN,"Metro: Alonso Martínez (líneas 4, 5 y 10), Tri...",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,BENEFICENCIA,...,CENTRO,440734,4475314,40.426355,-3.698666,914 452 560 / 609 876 913,NaN,anglicanspain@gmail.com,/contenido/entidadesYorganismos/TemplosOtrasRe...,
4,3388,Catedral Ortodoxa Griega. Santa Iglesia Catedr...,NaN,NaN,NaN,"Metro: Colombia (líneas 8 y 9). Bus: 11, 40, ...",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,NICARAGUA,...,CHAMARTIN,442946,4478760,40.457555,-3.672895,913 454 085 / 913 503 705,913 509 374,metropoliespo@yahoo.es,/contenido/entidadesYorganismos/TemplosOtrasRe...,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,11432588,Testigos Cristianos de Jehová. Calle Tembleque,NaN,NaN,NaN,"Metro: Empalme, Campamento (línea 5) Bus: 25,...",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,TEMBLEQUE,...,LATINA,435476,4471898,40.395189,-3.760301,915 188 149,NaN,NaN,/contenido/entidadesYorganismos/TemplosOtrasRe...,
294,189351,Testigos Cristianos de Jehová. Calle Venancio ...,NaN,NaN,NaN,Metro: Nueva Numancia (línea 1) Bus: 141 Bic...,NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,VENANCIO MARTIN,...,PUENTE DE VALLECAS,443866,4472138,40.397957,-3.661471,914 399 065,NaN,NaN,/contenido/entidadesYorganismos/TemplosOtrasRe...,
295,11731424,Testigos Cristianos de Jehová. Calle Ámbar,NaN,NaN,NaN,"Renfe Cercanías: Villaverde Bajo (C3, C4, C4a)",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,AMBAR,...,VILLA DE VALLECAS,447494,4469416,40.373674,-3.618489,917 977 863,NaN,NaN,/contenido/entidadesYorganismos/TemplosOtrasRe...,
296,11745450,The Korea Assemblies of God Full Gospel,Templo evangélico.,NaN,NaN,"Metro: Cuatro Caminos (líneas 1, 2 y 6). Bus:...",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,HERNANI,...,TETUAN,440586,4477736,40.448161,-3.700636,NaN,NaN,NaN,/contenido/entidadesYorganismos/TemplosOtrasRe...,
297,11773010,Yoido Full Gospel Madrid Church,Templo evangélico.,NaN,NaN,"Metro: Valdezarza (línea 7), Francos Rodríguez...",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,OFELIA NIETO,...,MONCLOA-ARAVACA,439837,4479117,40.460551,-3.709605,NaN,NaN,NaN,/contenido/entidadesYorganismos/TemplosOtrasRe...,

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 298 entries, 0 to 297
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PK                   298 non-null    int64
 1   NOMBRE               298 non-null    object
 2   DESCRIPCION-ENTIDAD  250 non-null    object
 3   HORARIO              0 non-null      float64
 4   EQUIPAMIENTO         0 non-null      float64
 5   TRANSPORTE           298 non-null    object
 6   DESCRIPCION          0 non-null      float64
 7   ACCESIBILIDAD        298 non-null    int64
 8   CONTENT-URL          298 non-null    object
 9   NOMBRE-VIA           298 non-null    object
 10  CLASE-VIAL           297 non-null    object
 11  TIPO-NUM             298 non-null    object
 12  NUM                  294 non-null    float64
 13  PLANTA               58 non-null     object
 14  PUERTA               41 non-null     object
 15  ESCALERAS            0 non-null      float64
 16  ORIENTACION          49 non-null     object
 17  LOCALIDAD            298 non-null    object
 18  PROVINCIA            298 non-null    object
 19  CODIGO-POSTAL        298 non-null    int64
 20  COD-BARRIO           298 non-null    int64
 21  BARRIO               298 non-null    object
 22  COD-DISTRITO         298 non-null    int64
 23  DISTRITO             298 non-null    object
 24  COORDENADA-X         298 non-null    int64
 25  COORDENADA-Y         298 non-null    int64
 26  LATITUD              298 non-null    float64
 27  LONGITUD             298 non-null    float64
 28  TELEFONO             41 non-null     object
 29  FAX                  1 non-null      object
 30  EMAIL                13 non-null     object
 31  TIPO                 298 non-null    object
 32  Unnamed: 32          298 non-null    object
dtypes: float64(7), int64(7), object(19)
memory usage: 77.0+ KB

In [58]:
df = df.drop(["PK","DESCRIPCION-ENTIDAD","HORARIO","EQUIPAMIENTO","DESCRIPCION","ACCESIBILIDAD","CONTENT-URL","TIPO-NUM",
              "PLANTA","PUERTA","ESCALERAS","ORIENTACION","LOCALIDAD","PROVINCIA","CODIGO-POSTAL","COD-DISTRITO","COD-BARRIO",
              "TELEFONO","FAX","EMAIL","Unnamed: 32","COORDENADA-X","COORDENADA-Y","BARRIO"],axis=1)

In [59]:
df['TIPO'] = df['TIPO'].str.extract(r'\/([^\/]+)$')

In [60]:
df["TIPO"].unique()

array(['TemplosOtrasReligiones'], dtype=object)

In [61]:
df.head()

,NOMBRE,TRANSPORTE,NOMBRE-VIA,CLASE-VIAL,NUM,DISTRITO,LATITUD,LONGITUD,TIPO
0,Asamblea Cristiana Gilgal,"Bus: 141, 133, 8.",GARGANTA DE AISA,CALLE,34.0,PUENTE DE VALLECAS,40.403023,-3.657575,TemplosOtrasReligiones
1,Asambleas de Evangelización Mundial para Crist...,"Metro: San Francisco (línea 11) Bus: 108, 118...",ANTONIA RODRIGUEZ SACRISTAN,CALLE,8.0,CARABANCHEL,40.372800,-3.745074,TemplosOtrasReligiones
2,Asociación Evangélica Internacional,"Metro: Colombia (líneas 8 y 9). Bus: 52, 11, ...",NICARAGUA,CALLE,19.0,CHAMARTIN,40.457895,-3.670675,TemplosOtrasReligiones
3,Catedral Anglicana de Madrid,"Metro: Alonso Martínez (líneas 4, 5 y 10), Tri...",BENEFICENCIA,CALLE,18.0,CENTRO,40.426355,-3.698666,TemplosOtrasReligiones
4,Catedral Ortodoxa Griega. Santa Iglesia Catedr...,"Metro: Colombia (líneas 8 y 9). Bus: 11, 40, ...",NICARAGUA,CALLE,12.0,CHAMARTIN,40.457555,-3.672895,TemplosOtrasReligiones

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 298 entries, 0 to 297
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   NOMBRE      298 non-null    object
 1   TRANSPORTE  298 non-null    object
 2   NOMBRE-VIA  298 non-null    object
 3   CLASE-VIAL  297 non-null    object
 4   NUM         294 non-null    float64
 5   DISTRITO    298 non-null    object
 6   LATITUD     298 non-null    float64
 7   LONGITUD    298 non-null    float64
 8   TIPO        298 non-null    object
dtypes: float64(3), object(6)
memory usage: 21.1+ KB

In [63]:
df["NUM"] = df["NUM"].fillna("N/A o N/D")

In [64]:
df["CLASE-VIAL"] = df["CLASE-VIAL"].fillna("No disponible")

In [65]:
# Intercambiamos el orden de las columnas 3 y 4 para luego cambiarles el nombre para favorecer la visualización.
df.iloc[:, [2, 3]] = df.iloc[:, [3, 2]].values

In [66]:
df.rename(columns={"NOMBRE-VIA": "CLASE-VIA", "CLASE-VIAL": "NOMBRE-VIA"}, inplace=True)

In [67]:
df["NUM"] = df["NUM"].astype(str)

In [68]:
df["DIRECCION"] = df["CLASE-VIA"] + " " + df["NOMBRE-VIA"] + " " + df["NUM"]

In [69]:
df.drop(["CLASE-VIA","NOMBRE-VIA","NUM"],axis=1,inplace=True)

In [70]:
df = df.loc[df["DISTRITO"].isin(["CENTRO", "CHAMBERI", "RETIRO","ARGANZUELA", "SALAMANCA"])]

In [71]:
df["DESCRIPCION"] = df["TIPO"]

In [72]:
df["TIPO"] = "Templos"

In [73]:
df.drop(["TRANSPORTE","DISTRITO"],axis=1,inplace=True)

In [74]:
df.head()

,NOMBRE,LATITUD,LONGITUD,TIPO,DIRECCION,DESCRIPCION
3,Catedral Anglicana de Madrid,40.426355,-3.698666,Templos,CALLE BENEFICENCIA 18.0,TemplosOtrasReligiones
17,Community Church of Madrid,40.444012,-3.718619,Templos,CALLE VIÑA 3.0,TemplosOtrasReligiones
23,Comunidad Cristiana Maranatha,40.405039,-3.680089,Templos,CALLE GRANADA 8.0,TemplosOtrasReligiones
27,Comunidad Evangélica de habla alemana,40.427213,-3.689422,Templos,PASEO CASTELLANA 6.0,TemplosOtrasReligiones
32,Iglesia Anglicana de San Jorge,40.426699,-3.682771,Templos,CALLE NUÑEZ DE BALBOA 43.0,TemplosOtrasReligiones

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34 entries, 3 to 286
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   NOMBRE       34 non-null     object
 1   LATITUD      34 non-null     float64
 2   LONGITUD     34 non-null     float64
 3   TIPO         34 non-null     object
 4   DIRECCION    34 non-null     object
 5   DESCRIPCION  34 non-null     object
dtypes: float64(2), object(4)
memory usage: 1.9+ KB

In [76]:
df = df.reindex(columns=['TIPO', 'NOMBRE', 'DIRECCION', 'DESCRIPCION', 'LATITUD', 'LONGITUD'])

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34 entries, 3 to 286
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TIPO         34 non-null     object
 1   NOMBRE       34 non-null     object
 2   DIRECCION    34 non-null     object
 3   DESCRIPCION  34 non-null     object
 4   LATITUD      34 non-null     float64
 5   LONGITUD     34 non-null     float64
dtypes: float64(2), object(4)
memory usage: 1.9+ KB

In [78]:
df

,TIPO,NOMBRE,DIRECCION,DESCRIPCION,LATITUD,LONGITUD
3,Templos,Catedral Anglicana de Madrid,CALLE BENEFICENCIA 18.0,TemplosOtrasReligiones,40.426355,-3.698666
17,Templos,Community Church of Madrid,CALLE VIÑA 3.0,TemplosOtrasReligiones,40.444012,-3.718619
23,Templos,Comunidad Cristiana Maranatha,CALLE GRANADA 8.0,TemplosOtrasReligiones,40.405039,-3.680089
27,Templos,Comunidad Evangélica de habla alemana,PASEO CASTELLANA 6.0,TemplosOtrasReligiones,40.427213,-3.689422
32,Templos,Iglesia Anglicana de San Jorge,CALLE NUÑEZ DE BALBOA 43.0,TemplosOtrasReligiones,40.426699,-3.682771
47,Templos,Iglesia Carismática Episcopal de España,CALLE BENEFICENCIA 18.0,TemplosOtrasReligiones,40.426351,-3.698683
48,Templos,Iglesia Catedral del Redentor,CALLE BENEFICENCIA 18.0,TemplosOtrasReligiones,40.426351,-3.698683
58,Templos,Iglesia Cristiana Adventista,CALLE ALENZA 6.0,TemplosOtrasReligiones,40.443575,-3.700490
62,Templos,Iglesia Cristiana Adventista del Séptimo Día. ...,CALLE ALENZA 6.0,TemplosOtrasReligiones,40.443565,-3.700500
81,Templos,Iglesia Cristiana Corazón de León,CALLE CARRETAS 14.0,TemplosOtrasReligiones,40.414988,-3.703425
96,Templos,Iglesia Cristiana Roca Eterna,PASEO DELICIAS 28.0,TemplosOtrasReligiones,40.404867,-3.693681
100,Templos,Iglesia Cruzada Cristiana Misión Vidaa,PASEO MOLINO 13.0,TemplosOtrasReligiones,40.390225,-3.693058
103,Templos,"Iglesia Cuerpo de Cristo, Don Pedro",CALLE DON PEDRO 10.0,TemplosOtrasReligiones,40.411644,-3.712768
113,Templos,Iglesia de los Discípulos de Cristo,CALLE PEDRO HEREDIA 3.0,TemplosOtrasReligiones,40.428383,-3.666094
117,Templos,Iglesia de Scientology de España,CALLE SANTA CATALINA 7.0,TemplosOtrasReligiones,40.415450,-3.697749
123,Templos,Iglesia Ejército de Salvación Madrid,CALLE HERMOSILLA 126.0,TemplosOtrasReligiones,40.425452,-3.667858
132,Templos,Iglesia Evangélica,CALLE CALATRAVA 25.0,TemplosOtrasReligiones,40.409237,-3.712074
136,Templos,Iglesia Evangélica Arca de Salvación,CALLE EUGENIO SELLES 1.0,TemplosOtrasReligiones,40.395808,-3.698617
152,Templos,Iglesia Evangélica Casa de Oración,CALLE LONDRES 13.0,TemplosOtrasReligiones,40.431461,-3.669450
162,Templos,Iglesia Evangélica Duque de Sesto,CALLE DUQUE DE SESTO 6.0,TemplosOtrasReligiones,40.422519,-3.678287
177,Templos,Iglesia Evangélica Filadelfia calle Oso 19,CALLE OSO 19.0,TemplosOtrasReligiones,40.409453,-3.705244
179,Templos,Iglesia Evangélica Filadelfia del Centro,CALLE RODRIGO DE GUEVARA 2.0,TemplosOtrasReligiones,40.409313,-3.708922
202,Templos,Iglesia evangélica Fundación Federico Fliedner,CALLE BRAVO MURILLO 85.0,TemplosOtrasReligiones,40.444938,-3.704210
203,Templos,Iglesia Evangélica Gran Rey,CALLE MAESTRO ARBOS 5.0,TemplosOtrasReligiones,40.390163,-3.694838
207,Templos,Iglesia Evangélica La Roca,PASEO DELICIAS 28.0,TemplosOtrasReligiones,40.404867,-3.693681
215,Templos,Iglesia Evangélica Noviciado 5,CALLE NOVICIADO 5.0,TemplosOtrasReligiones,40.425585,-3.708110
218,Templos,Iglesia Evangélica Pentecostal Amistad Cristiana,CALLE VALLEHERMOSO 70.0,TemplosOtrasReligiones,40.437257,-3.708287
227,Templos,Iglesia Evangélica Trafalgar,CALLE TRAFALGAR 32.0,TemplosOtrasReligiones,40.433711,-3.701242
242,Templos,Iglesia Misionera Pentecostal de Cristo,CALLE BENEFICENCIA 18.0,TemplosOtrasReligiones,40.426351,-3.698683
255,Templos,Iglesia Vida Apasionada,CALLE REYES MAGOS 8.0,TemplosOtrasReligiones,40.411570,-3.674760
257,Templos,Iglesia Vidapasionada,AVENIDA MENENDEZ PELAYO 36.0,TemplosOtrasReligiones,40.405437,-3.680375
266,Templos,Primera Iglesia Evangélica Bautista de Madrid,CALLE GENERAL LACY 18.0,TemplosOtrasReligiones,40.403587,-3.690929
276,Templos,Testigos Cristianos de Jehová. Calle Doctor Gó...,CALLE DOCTOR GÓMEZ ULLA 16.0,TemplosOtrasReligiones,40.429977,-3.667514
286,Templos,Testigos Cristianos de Jehová. Calle Martín de...,CALLE MARTIN DE VARGAS 26.0,TemplosOtrasReligiones,40.402441,-3.701735

In [79]:
nombre_archivo = "../data/madrid/Templos_no_catolicos/Templos_filtrados.csv"

In [80]:
df.to_csv(nombre_archivo)